USE [DB_A3EF3F_SUDOKU]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[Sp_InsertarCliente]
(
 
  @MAIL VARCHAR(50),
  @NOMBRE	VARCHAR(50),
  @USUARIO	VARCHAR(50),
  @PASSWORD VARCHAR(MAX),
  @FECHA DATETIME,
  @ESTADO VARCHAR(50)
)
AS
BEGIN

SET NOCOUNT ON;

INSERT INTO  CLIENTE (MAIL, NOMBRE, USUARIO, PASSWORD, FECHA, ESTADO) 
             VALUES
                     (@MAIL, @NOMBRE, @USUARIO, @PASSWORD, @FECHA, @ESTADO);
END 

